<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class LocationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('CityName', TextType::class)
            ->add('Country', ChoiceType::class, ['choices' => [
                'Afghanistan' => 'AF',
                'Albania' => 'AL',
                'Algeria' => 'DZ',
                'American Samoa' => 'AS',
                'Andorra' => 'AD',
                'Angola' => 'AO',
                'Antigua and Barbuda' => 'AG',
                'Azerbaijan' => 'AZ',
                'Australia' => 'AU',
                'Austria' => 'AT',
                'Bahamas' => 'BS',
                'Bahrain' => 'BH',
                'Bangladesh' => 'BD',
                'Armenia' => 'AM',
                'Barbados' => 'BB',
                'Belgium' => 'BE',
                'Bermuda' => 'BM',
                'Bhutan' => 'BT',
                'Bolivia' => 'BO',
                'Bosnia and Herzegovina' => 'BA',
                'Botswana' => 'BW',
                'Bouvet Island' => 'BV',
                'Brazil' => 'BR',
                'Belize' => 'BZ',
                'British Indian Ocean Territory' => 'IO',
                'Solomon Islands' => 'SB',
                'British Virgin Islands' => 'VG',
                'Brunei Darussalam' => 'BN',
                'Bulgaria' => 'BG',
                'Myanmar' => 'MM',
                'Burundi' => 'BI',
                'Belarus' => 'BY',
                'Cambodia' => 'KH',
                'Cameroon' => 'CM',
                'Canada' => 'CA',
                'Cape Verde' => 'CV',
                'Cayman Islands' => 'KY',
                'Central African' => 'CF',
                'Sri Lanka' => 'LK',
                'Chad' => 'TD',
                'Chile' => 'CL',
                'China' => 'CN',
                'Taiwan' => 'TW',
                'Christmas Island' => 'CX',
                'Cocos (Keeling) Islands' => 'CC',
                'Colombia' => 'CO',
                'Comoros' => 'KM',
                'Mayotte' => 'YT',
                'Republic of the Congo' => 'CG',
                'The Democratic Republic Of The Congo' => 'CD',
                'Cook Islands' => 'CK',
                'Costa Rica' => 'CR',
                'Croatia' => 'HR',
                'Cuba' => 'CU',
                'Cyprus' => 'CY',
                'Czech Republic' => 'CZ',
                'Benin' => 'BJ',
                'Denmark' => 'DK',
                'Dominica' => 'DM',
                'Dominican Republic' => 'DO',
                'Ecuador' => 'EC',
                'El Salvador' => 'SV',
                'Equatorial Guinea' => 'GQ',
                'Ethiopia' => 'ET',
                'Eritrea' => 'ER',
                'Estonia' => 'EE',
                'Faroe Islands' => 'FO',
                'Falkland Islands' => 'FK',
                'South Georgia and the South Sandwich Islands' => 'GS',
                'Fiji' => 'FJ',
                'Finland' => 'FI',
                'Åland Islands' => 'AX',
                'France' => 'FR',
                'French Guiana' => 'GF',
                'French Polynesia' => 'PF',
                'French Southern Territories' => 'TF',
                'Djibouti' => 'DJ',
                'Gabon' => 'GA',
                'Georgia' => 'GE',
                'Gambia' => 'GM',
                'Occupied Palestinian Territory' => 'PS',
                'Germany' => 'DE',
                'Ghana' => 'GH',
                'Gibraltar' => 'GI',
                'Kiribati' => 'KI',
                'Greece' => 'GR',
                'Greenland' => 'GL',
                'Grenada' => 'GD',
                'Guadeloupe' => 'GP',
                'Guam' => 'GU',
                'Guatemala' => 'GT',
                'Guinea' => 'GN',
                'Guyana' => 'GY',
                'Haiti' => 'HT',
                'Heard Island and McDonald Islands' => 'HM',
                'Vatican City State' => 'VA',
                'Honduras' => 'HN',
                'Hong Kong' => 'HK',
                'Hungary' => 'HU',
                'Iceland' => 'IS',
                'India' => 'IN',
                'Indonesia' => 'ID',
                'Islamic Republic of Iran' => 'IR',
                'Iraq' => 'IQ',
                'Ireland' => 'IE',
                'Israel' => 'IL',
                'Italy' => 'IT',
                'Côte d\'Ivoire' => 'CI',
                'Jamaica' => 'JM',
                'Japan' => 'JP',
                'Kazakhstan' => 'KZ',
                'Jordan' => 'JO',
                'Kenya' => 'KE',
                'Democratic People\'s Republic of Korea' => 'KP',
                'Republic of Korea' => 'KR',
                'Kuwait' => 'KW',
                'Kyrgyzstan' => 'KG',
                'Lao People\'s Democratic Republic' => 'LA',
                'Lebanon' => 'LB',
                'Lesotho' => 'LS',
                'Latvia' => 'LV',
                'Liberia' => 'LR',
                'Libyan Arab Jamahiriya' => 'LY',
                'Liechtenstein' => 'LI',
                'Lithuania' => 'LT',
                'Luxembourg' => 'LU',
                'Macao' => 'MO',
                'Madagascar' => 'MG',
                'Malawi' => 'MW',
                'Malaysia' => 'MY',
                'Maldives' => 'MV',
                'Mali' => 'ML',
                'Malta' => 'MT',
                'Martinique' => 'MQ',
                'Mauritania' => 'MR',
                'Mauritius' => 'MU',
                'Mexico' => 'MX',
                'Monaco' => 'MC',
                'Mongolia' => 'MN',
                'Republic of Moldova' => 'MD',
                'Montserrat' => 'MS',
                'Morocco' => 'MA',
                'Mozambique' => 'MZ',
                'Oman' => 'OM',
                'Namibia' => 'NA',
                'Nauru' => 'NR',
                'Nepal' => 'NP',
                'Netherlands' => 'NL',
                'Netherlands Antilles' => 'AN',
                'Aruba' => 'AW',
                'New Caledonia' => 'NC',
                'Vanuatu' => 'VU',
                'New Zealand' => 'NZ',
                'Nicaragua' => 'NI',
                'Niger' => 'NE',
                'Nigeria' => 'NG',
                'Niue' => 'NU',
                'Norfolk Island' => 'NF',
                'Norway' => 'NO',
                'Northern Mariana Islands' => 'MP',
                'United States Minor Outlying Islands' => 'UM',
                'Federated States of Micronesia' => 'FM',
                'Marshall Islands' => 'MH',
                'Palau' => 'PW',
                'Pakistan' => 'PK',
                'Panama' => 'PA',
                'Papua New Guinea' => 'PG',
                'Paraguay' => 'PY',
                'Peru' => 'PE',
                'Philippines' => 'PH',
                'Pitcairn' => 'PN',
                'Poland' => 'PL',
                'Portugal' => 'PT',
                'Guinea-Bissau' => 'GW',
                'Timor-Leste' => 'TL',
                'Puerto Rico' => 'PR',
                'Qatar' => 'QA',
                'Réunion' => 'RE',
                'Romania' => 'RO',
                'Russian Federation' => 'RU',
                'Rwanda' => 'RW',
                'Saint Helena' => 'SH',
                'Saint Kitts and Nevis' => 'KN',
                'Anguilla' => 'AI',
                'Saint Lucia' => 'LC',
                'Saint-Pierre and Miquelon' => 'PM',
                'Saint Vincent and the Grenadines' => 'VC',
                'San Marino' => 'SM',
                'Sao Tome and Principe' => 'ST',
                'Saudi Arabia' => 'SA',
                'Senegal' => 'SN',
                'Seychelles' => 'SC',
                'Sierra Leone' => 'SL',
                'Singapore' => 'SG',
                'Slovakia' => 'SK',
                'Vietnam' => 'VN',
                'Slovenia' => 'SI',
                'Somalia' => 'SO',
                'South Africa' => 'ZA',
                'Zimbabwe' => 'ZW',
                'Spain' => 'ES',
                'Western Sahara' => 'EH',
                'Sudan' => 'SD',
                'Suriname' => 'SR',
                'Svalbard and Jan Mayen' => 'SJ',
                'Swaziland' => 'SZ',
                'Sweden' => 'SE',
                'Switzerland' => 'CH',
                'Syrian Arab Republic' => 'SY',
                'Tajikistan' => 'TJ',
                'Thailand' => 'TH',
                'Togo' => 'TG',
                'Tokelau' => 'TK',
                'Tonga' => 'TO',
                'Trinidad and Tobago' => 'TT',
                'United Arab Emirates' => 'AE',
                'Tunisia' => 'TN',
                'Turkey' => 'TR',
                'Turkmenistan' => 'TM',
                'Turks and Caicos Islands' => 'TC',
                'Tuvalu' => 'TV',
                'Uganda' => 'UG',
                'Ukraine' => 'UA',
                'The Former Yugoslav Republic of Macedonia' => 'MK',
                'Egypt' => 'EG',
                'United Kingdom' => 'GB',
                'Isle of Man' => 'IM',
                'United Republic Of Tanzania' => 'TZ',
                'United States' => 'US',
                'U.S. Virgin Islands' => 'VI',
                'Burkina Faso' => 'BF',
                'Uruguay' => 'UY',
                'Uzbekistan' => 'UZ',
                'Venezuela' => 'VE',
                'Wallis and Futuna' => 'WF',
                'Samoa' => 'WS',
                'Yemen' => 'YE',
                'Serbia and Montenegro' => 'CS',
                'Zambia' => 'ZM'


            ], 
            'label' => 'Country'
        ])
            ->add('Change_location', SubmitType::class)
        
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            "test" => "test"
        ]);
    }
}
